apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts
spec:
  selector:
    matchLabels:
      app: posts
  replicas: 1
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: imagehostmad/posts:latest
          env:
            - name: RABBITMQ_CONN_STRING
              valueFrom:
                configMapKeyRef:
                  name: imagehost-config
                  key: RABBITMQ_URI
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: imagehost-config
                  key: MONGO_HOST
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: imagehost-secrets
                  key: MONGO_USERNAME
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: imagehost-secrets
                  key: MONGO_PASSWORD
          limits:
