apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts
spec:
  selector:
    matchLabels:
      app: posts
  replicas: 1
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: imagehostmad/posts:latest
          env:
            - name: JWT_HMAC_SECRET
              valueFrom:
                secretKeyRef:
                  name: imagehost-secrets
                  key: JWT_TOKEN_SECRET
            - name: RABBITMQ_CONN_URI
              valueFrom:
                configMapKeyRef:
                  name: imagehost-config
                  key: RABBITMQ_URI
            - name: MONGODB_HOST
              valueFrom:
                configMapKeyRef:
                  name: imagehost-config
                  key: MONGODB_HOST
            - name: MONGO_CONN_URI
              valueFrom:
                configMapKeyRef:
                  name: imagehost-config
                  key: MONGODB_URI
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: imagehost-secrets
                  key: MONGODB_USERNAME
            - name: MONGODB_PASS
              valueFrom:
                secretKeyRef:
                  name: imagehost-secrets
                  key: MONGODB_PASSWORD
          limits:
