apiVersion: apps/v1
kind: Deployment
metadata:
  name: userscripts
spec:
  selector:
    matchLabels:
      app: userscripts
  replicas: 1
  template:
    metadata:
      labels:
        app: userscripts
    spec:
      containers:
        - name: userscripts
          image: imagehostmad/userscripts:latest
          env:
            - name: MYSQL_URI
              valueFrom:
                configMapKeyRef:
                  name:  imagehost-config
                  key:  MYSQL_URI
            - name: AMQP_URI
              valueFrom:
                configMapKeyRef:
                  name: imagehost-config
                  key: RABBITMQ_URI
            - name:  MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name:  imagehost-secrets
                  key:  MYSQL_ROOT_PASSWORD
          limits:
