apiVersion: v1
kind: ConfigMap
metadata:
  name: imagehost-config
data:
  PROJECTNAME: ImageHost
  ORG_ID: imagehost.sdu.dk
  BASE_URL: http://localhost

  RABBITMQ_HOST: rabbitmq-0.rabbitmq.default.svc.cluster.local
  RABBITMQ_PORT: "5672"
  RABBITMQ_URI: amqp://guest:guest@rabbitmq-0.rabbitmq.default.svc.cluster.local # should not be used
  
  
  MYSQL_HOST: ""
  MYSQL_URI: jdbc:mysql://mysql:3306/
  
  MONGODB_HOST: ""
  MONGODB_URI: "mongodb://mongo-0.mongo,mongo-1.mongo,mongo-2.mongo/admin?replicaSet=rs0"

  POSTGRES_HOST: ""
  POSTGRES_URI: ""
