apiVersion: v1
kind: Secret
metadata:
  name: imagehost-secrets
type: Opaque
data:
  RABBITMQ_USERNAME: Z3Vlc3Q=
  RABBITMQ_PASSWORD: Z3Vlc3Q=
  RABBITMQ_ERLANG_COOKIE: VEZQWllJR01HR1JZSVVSQ1hQTlA=

  JWT_TOKEN_SECRET: c2VjcmV0
  
  MYSQL_USERNAME: c2VjcmV0
  MYSQL_ROOT_PASSWORD: c2VjcmV0

  MONGODB_USERNAME: c2VjcmV0
  MONGODB_PASSWORD: c2VjcmV0

  POSTGRESQL_USERNAME: c2VjcmV0
  POSTGRESQL_PASSWORD: c2VjcmV0