apiVersion: v1
kind: ConfigMap
metadata:
  name: imagehost-config
data:
  PROJECTNAME: ImageHost
  ORG_ID: imagehost.sdu.dk
  BASE_URL: http://localhost

  RABBITMQ_HOST: rabbitmq-0.rabbitmq.default.svc.cluster.local
  RABBITMQ_PORT: "5672"
  RABBITMQ_URI: amqp://guest:guest@rabbitmq-0.rabbitmq.default.svc.cluster.local # should not be used
  
  
  MYSQL_HOST: my-cluster-mysql-master 
  MYSQL_PORT: "3306"
  
  MONGODB_HOST: "mongo-db-mongodb-0.mongo-db-mongodb-headless.default.svc.cluster.local"
  MONGODB_URI: "mongodb://root:secret@mongo-db-mongodb-0.mongo-db-mongodb-headless.default.svc.cluster.local"

  POSTGRES_HOST: ""
  POSTGRES_URI: ""
