apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts
spec:
  selector:
    matchLabels:
      app: posts
  replicas: 1
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: imagehostmad/posts:latest
          env:
            - name: JWT_HMAC_SECRET
              valueFrom:
                secretKeyRef:
                  name: imagehost-secrets
                  key: JWT_TOKEN_SECRET
            - name: RABBITMQ_CONN_URI
              valueFrom:
                configMapKeyRef:
                  name: imagehost-config
                  key: RABBITMQ_URI
            - name: AMQP_USER
              valueFrom:
                secretKeyRef:
                  name: imagehost-secrets
                  key: RABBITMQ_USERNAME
            - name: AMQP_PASS
              valueFrom:
                secretKeyRef:
                  name: imagehost-secrets
                  key: RABBITMQ_PASSWORD
            - name: AMQP_HOST
              valueFrom:
                configMapKeyRef:
                  name: imagehost-config
                  key: RABBITMQ_HOST
            - name: AMQP_PORT
              valueFrom:
                configMapKeyRef:
                  name: imagehost-config
                  key: RABBITMQ_PORT
            - name: AMQP_VHOST
              value: "/"
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: imagehost-config
                  key: MONGODB_HOST
            - name: MONGO_CONN_URI
              valueFrom:
                configMapKeyRef:
                  name: imagehost-config
                  key: MONGODB_URI
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: imagehost-secrets
                  key: MONGODB_USERNAME
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: imagehost-secrets
                  key: MONGODB_PASSWORD
      initContainers:
      - name: init-rabbitmq
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup rabbitmq; do echo waiting for rabbitmq; sleep 20; done"]
