apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments
spec:
  selector:
    matchLabels:
      app: comments
  replicas: 1
  template:
    metadata:
      labels:
        app: comments
    spec:
      containers:
        - name: comments
          image: imagehostmad/comments:main
          env:
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: imagehost-config
                  key: RABBITMQ_HOST
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: imagehost-secrets
                  key: RABBITMQ_USERNAME
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: imagehost-secrets
                  key: RABBITMQ_PASSWORD
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name:  imagehost-config
                  key:  RABBITMQ_PORT
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name:  imagehost-config
                  key:  MYSQL_HOST
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name:  imagehost-config
                  key:  MYSQL_PORT
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key:  USERNAME
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name:  mysql-secrets
                  key:  ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: "Comments"
      initContainers:
      - name: init-rabbitmq
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup rabbitmq; do echo waiting for rabbitmq; sleep 5; done"]
      - name: init-mysql
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup my-cluster-mysql; do echo waiting for mysql; sleep 5; done"]
