apiVersion: apps/v1
kind: Deployment
metadata:
  name: userscripts
spec:
  selector:
    matchLabels:
      app: userscripts
  replicas: 1
  template:
    metadata:
      labels:
        app: userscripts
    spec:
      serviceAccountName: userscripts
      containers:
        - name: userscripts
          image: imagehostmad/user-scripts:latest
          env:        
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: imagehost-secrets
                  key: RABBITMQ_USERNAME
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: imagehost-secrets
                  key: RABBITMQ_PASSWORD
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: imagehost-config
                  key: RABBITMQ_HOST
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: imagehost-config
                  key: MONGODB_HOST
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: imagehost-secrets
                  key: MONGODB_PASSWORD
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: imagehost-secrets
                  key: MONGODB_USERNAME
          initContainers:
          - name: init-rabbitmq
            image: busybox:1.28
            command: ['sh', '-c', "until nslookup rabbitmq; do echo waiting for rabbitmq; sleep 20; done"]
          limits:
          volumeMounts:
            - name: userscripts-persistent-storage
              mountPath: /app/user_scripts/
      volumes:
        - name: userscripts-persistent-storage
          persistentVolumeClaim:
            claimName: userscripts-pv-claim
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: userscripts-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/userscripts/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: userscripts-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
