apiVersion: apps/v1
kind: Deployment
metadata:
  name: likes
spec:
  selector:
    matchLabels:
      app: likes
  replicas: 1
  template:
    metadata:
      labels:
        app: likes
    spec:
      containers:
        - name: likes
          image: imagehostmad/likes:latest
          env:
            - name: AMQP_URI
              valueFrom:
                configMapKeyRef:
                  name: imagehost-config
                  key: RABBITMQ_URI
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name:  imagehost-config
                  key:  MYSQL_HOST
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name:  imagehost-config
                  key:  MYSQL_PORT
            - name:  MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name:  mysql-secrets
                  key:  ROOT_PASSWORD
            - name: MYSQL_DB
              value: "Likes"
          limits:
