apiVersion: apps/v1
kind: Deployment
metadata:
  name: likes
spec:
  selector:
    matchLabels:
      app: likes
  replicas: 1
  template:
    metadata:
      labels:
        app: likes
    spec:
      containers:
        - name: likes
          image: lass7965/likes:latest
          env:
            - name: MYSQL_URI
              valueFrom:
                configMapKeyRef:
                  name:  imagehost-config
                  key:  MYSQL_URI
            - name: AMQP_URI
              valueFrom:
                configMapKeyRef:
                  name: imagehost-config
                  key: RABBITMQ_URI
            - name:  MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name:  imagehost-secrets
                  key:  MYSQL_ROOT_PASSWORD
          limits:
