apiVersion: apps/v1
kind: Deployment
metadata:
  name: imagestorage
spec:
  selector:
    matchLabels:
      app: imagestorage
  replicas: 1
  template:
    metadata:
      labels:
        app: imagestorage
    spec:
      containers:
        - name: imagestorage
          image: imagehostmad/imagestorage:latest
          env: #Needs to check that this is the env needed
        - name: tags
          image: imagehostmad/tags:latest
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name:  imagehost-config
                  key:  MYSQL_HOST
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name:  imagehost-config
                  key:  MYSQL_PORT
            - name:  MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name:  mysql-secrets
                  key:  ROOT_PASSWORD
          limits:
