apiVersion: apps/v1
kind: Deployment
metadata:
  name: imagestorage
spec:
  selector:
    matchLabels:
      app: imagestorage
  replicas: 1
  template:
    metadata:
      labels:
        app: imagestorage
    spec:
      containers:
        - name: imagestorage
          image: imagehostmad/imagestorage:v0.9.1
          env:
            - name: AMQP_HOST
              valueFrom:
                configMapKeyRef:
                  name: imagehost-config
                  key: RABBITMQ_HOST
            - name: AMQP_USER
              valueFrom:
                secretKeyRef:
                  name: imagehost-secrets
                  key: RABBITMQ_USERNAME
            - name: AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: imagehost-secrets
                  key: RABBITMQ_PASSWORD
            - name: AMQP_PORT
              valueFrom:
                configMapKeyRef:
                  name: imagehost-config
                  key: RABBITMQ_PORT
            - name: DB_DRIVER
              value: com.mysql.jdbc.Driver
            - name: DB_URI
              value: jdbc:mysql://my-cluster-mysql-master:3306/imagestorage
            - name:  DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name:  mysql-secrets
                  key:  ROOT_PASSWORD
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name:  mysql-secrets
                  key:  USERNAME
          limits:
