apiVersion: apps/v1
kind: Deployment
metadata:
  name: imageencoding
spec:
  selector:
    matchLabels:
      app: imageencoding
  replicas: 1
  template:
    metadata:
      labels:
        app: imageencoding
    spec:
      containers:
        - name: imageencoding
          image: imagehostmad/imageencoding:latest
          env: #needs to be looked at
            - name: MYSQL_URI
              valueFrom:
                configMapKeyRef:
                  name:  imagehost-config
                  key:  MYSQL_URI
            - name: AMQP_URI
              valueFrom:
                configMapKeyRef:
                  name: imagehost-config
                  key: RABBITMQ_URI
            - name:  MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name:  imagehost-secrets
                  key:  MYSQL_ROOT_PASSWORD
          limits:
