apiVersion: v1
kind: Service
metadata:
  name: webgateway
  labels:
    app: webgateway
spec:
  type: LoadBalancer
  selector:
    app: webgateway
  ports:
    - protocol: TCP
      name: http
      port: 5000
      targetPort: 5000


#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: basic-ingress
#spec:
#  backend:
#    serviceName: webgateway
#    servicePort: 5000