apiVersion: apps/v1
kind: Deployment
metadata:
  name: tags
spec:
  selector:
    matchLabels:
      app: tags
  replicas: 1
  template:
    metadata:
      labels:
        app: tags
    spec:
      containers:
        - name: tags
          image: imagehostmad/tags:latest
          env:
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: imagehost-config
                  key: RABBITMQ_HOST
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: imagehost-secrets
                  key: RABBITMQ_USERNAME
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: imagehost-secrets
                  key: RABBITMQ_PASSWORD
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name:  imagehost-config
                  key:  RABBITMQ_PORT
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name:  imagehost-config
                  key:  MYSQL_HOST
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key:  USERNAME
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name:  mysql-secrets
                  key:  ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: "Tags"
            - name: SECRET_KEY
              value: "secret"
          limits:
