apiVersion: v1
kind: Secret
metadata:
  name: webgateway
type: Opaque
data:
  RABBIT_USERNAME: Z3Vlc3Q= # base64 'guest'
  RABBIT_PASSWORD: Z3Vlc3Q= # base64 'guest'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webgateway
  labels:
    app: webgateway
spec:
  selector:
    matchLabels:
      app: webgateway
  replicas: 1
  template:
    metadata:
      labels:
        app: webgateway
    spec:
      containers:
      - name: webgateway
        image: imagehostmad/web-gateway
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: AMQP_URI 
          value: "rabbitmq-0.rabbitmq.default.svc.cluster.local"
        - name: RABBIT_PORT
          value: "5672"
        - name: RABBIT_USER
          valueFrom:
            secretKeyRef:
              name: webgateway
              key: RABBIT_USERNAME
        - name: RABBIT_PASS
          valueFrom:
            secretKeyRef:
              name: webgateway
              key: RABBIT_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: webgateway
  labels:
    app: webgateway
spec:
  type: LoadBalancer
  selector:
    app: webgateway
  ports:
    - protocol: TCP
      name: http
      port: 5000
      targetPort: 5000