name: Configuration validator
on: [push]

jobs:
  k8s-validation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: validate
      uses: instrumenta/kubeval-action@master
      with:
        files:  ./kubernetes-flattened
        strict: false
