name: Configuration validator
on: [push]

jobs:
  k8s-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: validate manifest-dir
        uses: makocchi-git/actions-k8s-manifests-validate-conftest@1.1.0
        with:
          file: ./kubernetes-flattened
          comment: false
          #token: ${{ secrets.GITHUB_TOKEN }}
